### ISSUE TITLE
No temp or offset text are shown when installed

### ISSUE THREAD

**Issue by Gorkamora** [wabbitguy/Kobra_Plus#1]
The screen UI was successfully installed, but the top of the screen is missing the temperature text, and when going to the about section, no text can be seen.
![IMG_6232](https://github.com/wabbitguy/Kobra_Plus/assets/136536500/99ffb7fc-9d63-430e-b60f-8b6101892d7e)
![IMG_6233](https://github.com/wabbitguy/Kobra_Plus/assets/136536500/828c8526-7810-41fc-904a-9fc290f75aa0)

**Comment by wabbitguy** [comment]
@Gorkamora all information for the display comes from the motherboard in the printer, so it looks like the motherboard has no communication happening at all. Have you flashed the firmware for the motherboard as well or just using the factory stock firmware?

**Comment by Gorkamora** [comment]
Hi @wabbitguy! I did flash the board firmware and I believe it’s all working correctly. For the time being, I have reinstalled the stock screen firmware  from the kobra max download from the Anycubic website (kobra plus didn’t include screen firmware on the website). This seems to fix the issue, did one bed level test print and it turned out great.

**Comment by wabbitguy** [comment]
@Gorkamora I'll check it out and get back to you.

**Comment by wabbitguy** [comment]
@Gorkamora I had three users test the LCD DWIN SET and it works fine so the only thing that would be causing an issue with no info showing up would be the firmware on the motherboard (the 1.8.3) version. But we can't duplicate the issue you see.

If you select "Settings-->About" you should see this version info in the LCD. If that's correct, it doesn't really make any sense why the motherboard is not sending info to the LCD.

<img width="520" alt="Monosnap 2023-06-16 17-32-27" src="https://github.com/wabbitguy/Kobra_Plus/assets/8953419/f563dbf3-1d4b-4ad0-a028-02f54e093565">

**Comment by Gorkamora** [comment]
I’ll try it out again tonight and let you know if it works.

**Comment by Gorkamora** [comment]
@wabbitguy Sorry for taking a while to write back, I reinstalled the UI and it's working great! Loving both the new UI and Firmware! Thank you for this amazing firmware set and getting back so quick!

**Comment by wabbitguy** [comment]
@Gorkamora no worries! Great to hear it's working for you. Have fun printing!!!!!

Mel
