### ISSUE TITLE
Kobra Plus modified with direct drive

### ISSUE THREAD

**Issue by Oxyg3nius** [wabbitguy/Kobra_Plus#5]
Hi wabbitguy,

at first: I love your firmware. It makes my work so much easier. Especially the filament change at last. GREAT :)

My question is: I have modified my printer with an direct drive extruder and every time I change the filament, at first feeds the filament at high speed. However, the extruder blocks as it sits directly on the hotend. Is it possible to create a firmware for the direct drive, whereby it leaves out the part with the fast feed when changing or fill in the filament? That woud be great. :) 

Thx.
greetings from germany

**Comment by wabbitguy** [comment]
@Oxyg3nius there's two sections where the load/unloading is done. First when you use the "Prepare" load filament (or unload). The second is if you don't a M600 filament change. Lengths for those are in the firmware and for a modified hot end, there'd have to be some measurements taken and then the firmware adjusted to compensate for the modification.

I'd need to know the distance, in mm (as accurate as you can get it) the length from the extruder gears to the nozzle tip. From there I could try to create a custom one up version of the firmware for you.

I'm going to close this issue but you'll still be able to leave messages here via direct links you'll get.

Mel - aka the WabbitGuy

p.s. Hi from Vancouver Canada!
---

**Comment by Oxyg3nius** [comment]
Hi Mel,

I measured about 100mm till Heatbreak (and another 30mm till nozzle). But I would choose 80mm for fast feed, to be on the safe side and maybe 50 mm more for slow feed. Here it doesn't matter if I lose more filament, but so I can be sure that old filament is also out of the heatblock.

The unload section works perfect for me.

Here you can see the mod which I use:
https://www.thingiverse.com/thing:5623650

Thank you and have a great day

Mario

**Comment by wabbitguy** [comment]
@Oxyg3nius changed according to your suggestion/measurement. Think I got it right. And your printer also has a new name to identify it. Let me know if it works the way you want it to.

[firmware.bin.zip](https://github.com/wabbitguy/Kobra_Plus/files/13745799/firmware.bin.zip)

**Comment by Oxyg3nius** [comment]
@wabbitguy  Thank you for the fast implementation.  I test it directly. 
The fast feeding works perfect. But after this, the slow feeding is not enough. Only 2-3 cm of filament comes out. It is possible to increase this value by 100mm? (or the same as in your other firmware +50mm more)

Thank you :)

**Comment by wabbitguy** [comment]
@Oxyg3nius updates as requested. Not sure why it needs a lot more but it should be closer now. Fingers crossed.

[firmware.bin.zip](https://github.com/wabbitguy/Kobra_Plus/files/13757032/firmware.bin.zip)

**Comment by Oxyg3nius** [comment]
Mel, you are Genius. :) Now, it works perfect. Thank you so much.

**Comment by wabbitguy** [comment]
@Oxyg3nius awesome! Not a genius, just a retired software developer with way too much time on my hands sometimes...ROFLOL..

Have a GREAT Christmas and all the best in the New Year!

**Comment by Oxyg3nius** [comment]
I also wish you a Merry Christmas and stay healthy.
